# environment.yml

name: anomaly-detect
channels:
  - conda-forge
  - defaults

dependencies:
  # Base Python
  - python>=3.10

  # Core ML stack
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.3.2
  - tensorflow=2.15.0
  - joblib=1.4.0

  # Packet analysis
  - scapy=2.5.0

  # Visualisation
  - matplotlib=3.8.3
  - seaborn=0.13.2

  # Utilities
  - pyyaml=6.0.1
  - tqdm=4.67.1
  - requests=2.32.3

  # Installed via pip
  - pip
  - pip:
      - pyshark==0.6