# pyproject.toml

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anomaly-detect"
version = "1.0.6"
description = "Anomaly-Based Threat Detection Pipeline using Machine Learning"
authors = [
  { name = "William Jecks", email = "p2721974@my365.dmu.ac.uk" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy==1.26.4",
  "pandas==2.2.3",
  "scikit-learn==1.3.2",
  "tensorflow==2.15.0",
  "joblib==1.4.0",
  "pyyaml==6.0.1",
  "scapy==2.5.0",
  "matplotlib==3.8.3",
  "seaborn==0.13.2",
  "pyshark==0.6",
  "requests==2.32.3",
  "tqdm==4.67.1",
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/twisted-care/anomaly-detect

[project.scripts]
anomaly-detect = "cli.main:main"
