# === Capture Settings ===
capture:
  interface: en0
  duration: 30
  packet_count: 100
  output_path: data/captures/capture.pcap

# === Preprocessing Settings ===
preprocessing:
  batch_size: 1000
  label: Null
  pcap_input: data/captures/capture.pcap
  csv_output: data/processed/preprocessed.csv

# === Dataset Utils Settings ===
dataset_utils:
  output_path: data/combined/combined.csv

# === Training Settings ===
training:
  input: data/preprocessed/train.csv
  save_dir: data/models/
  model_type: autoencoder
  n_estimators: 100

# === Detection Settings ===
detection:
  input_path: data/processed/test.csv
  model_type: autoencoder
  model_path: data/models/autoencoder/autoencoder_model
  csv_output: data/detection/detection.csv
  threshold: 0.5

# === SIEM / Wazuh Integration ===
siem:
  mode: file    # Options: file, syslog, both
  log_path: data/logs/alerts.log
  syslog_host: 127.0.0.1
  syslog_port: 514
